I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 33, in script call
    call ch2_main from _call_ch2_main
  File "game/script-ch2.rpy", line 54, in script
    $ s_face = flirty
  File "game/script-ch2.rpy", line 54, in <module>
    $ s_face = flirty
NameError: name 'flirty' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 33, in script call
    call ch2_main from _call_ch2_main
  File "game/script-ch2.rpy", line 54, in script
    $ s_face = flirty
  File "C:\Program Files (x86)\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files (x86)\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script-ch2.rpy", line 54, in <module>
    $ s_face = flirty
NameError: name 'flirty' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
Genshou Girls Festival 1.0
Fri Dec  9 06:11:00 2022
